### ISSUE TITLE
Languages dropdown on User Verse Assignment should be populated from API

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#50]
The languages dropdown on the User Verse Assignment page should get its data from the API call. There is a Language model (located here: https://github.com/lifechurch/img-src/blob/master/src/tupos/models/language/index.js) that you use to fetch the list of available languages using the `getMany()` method. For example:

```javascript
import Language from './tupos/models/language'
const languages = await Language.getMany()
const languageItems = languages.map((language) => (
  <li>{language.name}</li>
))
```

**Comment by mroche617** [comment]
lanaguages.data[0]: {language_tag: "eng", name: "English", local_name: "English"}

There is no value attribute in the language's object, which is required for the Combo-box

**Comment by borozcod** [comment]
Hi @mroche617 I remember building the Combo-Box component a few weeks back. If it needs updating for this specific issue feel free to do so. You might be able to do something like `const newObject = Object.assign({}, oldObject,  { value:  oldObject.language_tag })`;  and pass in that new object with the value key instead of `language_tag`. I'm assuming `language_tag` is what we would use as the "value" for say.

**Comment by mroche617** [comment]
@michael-martin-al is the correct value the language-tag?  If so we can use a method like @borozcod suggested.  The details in the original language array has upper case  values like EN or ES (which are equal to window.navigator.language)

**Comment by michael-martin-al** [comment]
@mroche617 have you rebased with `master` yet? I found an older PR that I had overlooked, and I merged it a couple of days ago. That PR included some of the work that you're working on. I apologize for overlooking that.
